# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-03 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Doing', 'Doing')], default='Doing', max_length=6),
        ),
    ]
