# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-09 22:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('phase_of_development', models.CharField(choices=[('Done', 'Done'), ('Doing', 'Doing'), ('ToDo', 'ToDo')], default='ToDo', max_length=6)),
                ('upvote', models.IntegerField(default=0)),
                ('vote_price', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
