# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-05 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20200303_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upvotefeature',
            old_name='upvoted_feature',
            new_name='upvote_feature',
        ),
    ]
