# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-05 17:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0003_auto_20200305_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='upvotefeature',
            name='upvote_feature',
        ),
        migrations.RemoveField(
            model_name='upvotefeature',
            name='user',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='details',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='in_progress_date',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='username',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='waiting_date',
        ),
        migrations.AddField(
            model_name='feature',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('todo', 'To do'), ('doing', 'Doing'), ('done', 'Done')], default='todo', max_length=5),
        ),
        migrations.DeleteModel(
            name='UpvoteFeature',
        ),
        migrations.AddField(
            model_name='featurecomment',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Feature'),
        ),
    ]
